navsat_transform_node:
  ros__parameters:
    frequency: 30.0
    delay: 3.0
    magnetic_declination_radians: 0.19722
    yaw_offset: 0.0
    zero_altitude: true
    use_odometry_yaw: false
    publish_filtered_gps: true
    broadcast_utm_transform: true
    broadcast_utm_transform_as_parent_frame: true

